spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:db}
    username: ${POSTGRES_USER:postgres}
    password: ${PGPASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create

api:
 security:
    token:
        secret: ${JWT_SECRET:my-secret-key}

user:
    mock:
        username: admin@admin.com
        password: ${PGPASSWORD:Senha1234}

server:
  port: 8080