spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update

api:
 security:
    token:
        secret: ${JWT_SECRET:my-secret-key}

user:
    mock:
        username: ${ADMIN_USER:admin@admin.com}
        password: ${ADMIN_PASS:Senha1234}
        
server:
  port: 8080